<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
    <PackageReference Include="PolyShim" PrivateAssets="all" />
    <PackageReference Include="PowerKit" PrivateAssets="all" />
    <PackageReference Include="QuickJson" PrivateAssets="all" />
    <PackageReference Include="System.IO.Compression" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Management" />
  </ItemGroup>
</Project>
